name: Build App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo wget -nc -O /usr/share/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -nc -P /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
          sudo apt update
          sudo apt-get install --install-recommends winehq-stable
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npm run build-linux
          npm run build-windows
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apps
          path: |
            screen-linux.zip
            screen-windows.zip
          retention-days: 3
