name: Build App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Wine
        run: |
          sudo apt-get update
          sudo apt-get install wine-stable
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npm run build-linux
          npm run build-windows
      - name: Upload linux
        uses: actions/upload-artifact@v3
        with:
          name: linux.zip
          path: screen-linux.zip
          retention-days: 3
      - name: Upload windows
        uses: actions/upload-artifact@v3
        with:
          name: windows.zip
          path: screen-windows.zip
          retention-days: 3
