name: Build App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npm run build-linux
          npm run build-windows
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt install software-properties-common
          sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
          sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
          sudo apt update
          sudo apt-get install --install-recommends winehq-stable
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apps
          path: |
            screen-linux.zip
            screen-windows.zip
          retention-days: 3
